name = "Sumcheck"
uuid = "84d44fc1-a790-4315-927d-a798c59cc72a"
authors = ["Andrija <akinovak@gmail.com>", "guille <guille@angeris.net>"]
version = "0.1.0"

[deps]
BinaryFields = "0fee9d7f-8397-4f0d-9ec6-117db1666467"
BinaryReedSolomon = "8a283c49-c6d0-46c5-bbc1-5b2a51f34960"
MultilinearPoly = "738c1076-b784-4255-a602-5a9e144980bc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
BinaryFields = "0.1.0"
MultilinearPoly = "0.1.0"
Test = "1.11.0"
